### ISSUE TITLE
English transcript

### ISSUE THREAD

**Issue by aromot** [jmosbech/spell-it#6]
Hello,

142 gives "one hundred forty-two". From the English I took and confirmed by a method called "Calling All Beginners" (BBC edition), it should be "one hundred AND forty-two".

**Comment by jmosbech** [comment]
Thanks for chipping in. 

As far as I know [this variation is accepted in american english](https://en.wikipedia.org/wiki/Comparison_of_American_and_British_English#Numbers). However, I would gladly accept a pull request that adds support for both en-gb and en-us. :)

**Comment by aromot** [comment]
I can't open a new Pull Request... when I try, I get : "Compare changes
Compare changes across branches, commits, tags, and more below. If you need to, you can also  compare across forks." I don't understand why. The button "Create pull request" is desabled. Can you help?

**Comment by jmosbech** [comment]
Did you create a fork of the repo?

**Comment by aromot** [comment]
No, do I need to?

**Comment by jmosbech** [comment]
Yeah - check this out if you need help:

https://help.github.com/articles/creating-a-pull-request-from-a-fork/
