### ISSUE TITLE
Wrong rule for French "cent/cents"

### ISSUE THREAD

**Issue by samueltardieu** [jmosbech/spell-it#8]
The code contains

    // when cent is at the end of the number, it takes an s, but when it's followed by another number, the s is dropped.

This is wrong: if it is at the end of a number and preceeded by a number smaller than "cent" (for example "quatre-cents" for 400) it takes a "s" at the end, since it means 4*100, but when the number before is greater than 100 ("mille-cent" for 1100) it does not take a "s", it does not mean 1000*100 but 1000+100 (one thousand + **one** hundred, hence no "s").

You can use https://rfc1149.net/documents/nombres-francais.txt as a reference to check the output.

**Comment by jmosbech** [comment]
Good catch. 👍 I will gladly merge a patch, but otherwise a fix will go on my to do list.

**Comment by jmosbech** [comment]
By the way I'm pretty sure that rule was pulled from [here](https://www.thoughtco.com/french-numbers-nombres-1372760).

**Comment by samueltardieu** [comment]
The full rule that you quote says

> In French, 100 to 999 work just like in English - just say how many hundreds and then add the other numbers. Note that when cent is at the end of the number, it takes an s, but when it's followed by another number, the s is dropped.

So to get a "s" you need to have several hundreds. "Mille-cent" is "One thousand and one hundred", not "one thousand hundreds", so the plural cannot be used (hence no "s" at "cent" there).

You can check the result for a particular number there: http://www.chiffre-en-lettre.fr/ecrire-nombre-1100-mille-cent
